// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMDz8pI-twC17IAtHxX1JLWTUesg7KC0',
    appId: '1:248679678992:web:475c50de5e68e03cd07695',
    messagingSenderId: '248679678992',
    projectId: 'technews-bc871',
    authDomain: 'technews-bc871.firebaseapp.com',
    storageBucket: 'technews-bc871.appspot.com',
    measurementId: 'G-CXEDH1ZP4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuONyBI_pWhVEk9voM1FX7VfG42Q1UeE0',
    appId: '1:248679678992:android:8a8de89e4cc8470bd07695',
    messagingSenderId: '248679678992',
    projectId: 'technews-bc871',
    storageBucket: 'technews-bc871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPB6Lstl6VuaXBSfsIx8jXlLaT3Q1E9UE',
    appId: '1:248679678992:ios:688cddb8afcaa2cdd07695',
    messagingSenderId: '248679678992',
    projectId: 'technews-bc871',
    storageBucket: 'technews-bc871.appspot.com',
    iosBundleId: 'com.example.technews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPB6Lstl6VuaXBSfsIx8jXlLaT3Q1E9UE',
    appId: '1:248679678992:ios:45c4ebeaf4c35e51d07695',
    messagingSenderId: '248679678992',
    projectId: 'technews-bc871',
    storageBucket: 'technews-bc871.appspot.com',
    iosBundleId: 'com.example.technews.RunnerTests',
  );
}
